# Site settings
email: studio@xxix.co
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Serial Box: Web application, iOS application and Blog (Tumblr).
baseurl: "/serialbox-docs" # the subpath of your site, e.g. /blog/
client: "Serial Box"

# Build settings
markdown: kramdown
